### ISSUE TITLE
[Manual] Unknown word "with" in lesson VI

### ISSUE THREAD

**Issue by precondition** [Sillabix/Midi4Text-ortographic-system#2]
The end of lesson VI contains the following sentence as exercise:
> An issue has ceased with a deed.

However, one of those words, "with ", is not writeable with the current knowledge of the manual reader so far.

Initial W is addressed only in Lesson X and ending TH is introduced in Lesson XV.

Suggestion: replace the sentence in Lesson VI by 
> An issue has ceased a deed.

**Comment by Sillabix** [comment]
Thanks, fixed this in version 1.3.5 of the manual
